name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-java@v2
        with:
            distribution: 'zulu'
            java-version: '11'
            java-package: jdk
            
      - name: Run tests
        run: ./gradlew test
